---
provides: [caliptra_ss_lc_ctrl_pkg]
schema_version: 2.4.0
requires: 
  - caliptra_prim_pkg
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/jtag_pkg.sv
      - $COMPILE_ROOT/rtl/top_pkg.sv
      - $COMPILE_ROOT/rtl/alert_handler_reg_pkg.sv
  tb:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/jtag_pkg.sv
      - $COMPILE_ROOT/rtl/top_pkg.sv
      - $COMPILE_ROOT/rtl/alert_handler_reg_pkg.sv
---
provides: [lc_kmac_pkg]
schema_version: 2.4.0
requires:
  - caliptra_prim_pkg
  - lc_ctrl_pkg
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/lc_ctrl_keymgr_pkg.sv
      - $COMPILE_ROOT/rtl/kmac_reg_pkg.sv
      - $COMPILE_ROOT/rtl/caliptra_ss_sha3_pkg.sv
      - $COMPILE_ROOT/rtl/kmac_pkg.sv
  tb:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/lc_ctrl_keymgr_pkg.sv
      - $COMPILE_ROOT/rtl/kmac_reg_pkg.sv
      - $COMPILE_ROOT/rtl/caliptra_ss_sha3_pkg.sv
      - $COMPILE_ROOT/rtl/kmac_pkg.sv
---
provides: [lc_ctrl]
schema_version: 2.4.0
requires:
  - caliptra_ss_lc_ctrl_pkg
  - lc_ctrl_pkg
  - lc_kmac_pkg
  - axi_pkg
  - axi2tlul
  - tlul_pkg
  - pwrmgr_pkg
  - fuse_ctrl_pkg
  - ast_pkg
  - edn_pkg
  - tlul
  - dmi_jtag
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/caliptra_ss_keccak_2share.sv
      - $COMPILE_ROOT/rtl/caliptra_ss_keccak_round.sv
      - $COMPILE_ROOT/rtl/caliptra_ss_sha3pad.sv
      - $COMPILE_ROOT/rtl/caliptra_ss_sha3.sv
      - $COMPILE_ROOT/rtl/kmac_app.sv
      - $COMPILE_ROOT/rtl/kmac_core.sv
      - $COMPILE_ROOT/rtl/kmac_entropy.sv
      - $COMPILE_ROOT/rtl/kmac_errchk.sv
      - $COMPILE_ROOT/rtl/kmac_msgfifo.sv
      - $COMPILE_ROOT/rtl/kmac_reduced.sv
      - $COMPILE_ROOT/rtl/kmac_reg_top.sv
      - $COMPILE_ROOT/rtl/kmac_staterd.sv
      - $COMPILE_ROOT/rtl/kmac.sv
      - $COMPILE_ROOT/rtl/lc_ctrl_fsm.sv
      - $COMPILE_ROOT/rtl/lc_ctrl_kmac_if.sv
      - $COMPILE_ROOT/rtl/lc_ctrl_reg_top.sv
      - $COMPILE_ROOT/rtl/lc_ctrl_signal_decode.sv
      - $COMPILE_ROOT/rtl/lc_ctrl_state_decode.sv
      - $COMPILE_ROOT/rtl/lc_ctrl_state_transition.sv
      - $COMPILE_ROOT/rtl/lc_ctrl.sv 
    tops: [lc_ctrl]
