provides: [i3c-core]
schema_version: 2.4.0
requires:
  - axi_sub
  - caliptra_prim_pkg
targets:
  tb:
    directories:
      - $COMPILE_ROOT/../../third_party/i3c-core/src
    files:
      - $COMPILE_ROOT/../../third_party/i3c-core/src/i3c_defines.svh
  rtl:
    directories:
      - $COMPILE_ROOT/../../third_party/i3c-core/src
      - $COMPILE_ROOT/../../third_party/i3c-core/src/libs/axi
    files:
      - $COMPILE_ROOT/../../third_party/i3c-core/src/libs/mem/prim_ram_1p_pkg.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/libs/mem/prim_generic_ram_1p.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/libs/mem/prim_ram_1p_adv.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/libs/mem/prim_ram_1p.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/csr/I3CCSR_pkg.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/controller_pkg.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/i3c_pkg.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/phy/buf_od.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/phy/buf_pp.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/phy/bufs.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/phy/i3c_phy.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/phy/i3c_io.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/csr/I3CCSR.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/hci/queues/read_queue.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/hci/queues/write_queue.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/hci/ahb_if.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/hci/axi_adapter.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/hci/dxt.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/hci/tti.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/hci/queues.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/hci/hci.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/target_reset_detector.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/width_converter_8toN.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/width_converter_Nto8.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/recovery/recovery_pec.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/recovery/recovery_receiver.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/recovery/recovery_transmitter.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/recovery/recovery_executor.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/recovery/recovery_handler.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/bus_timers.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/bus_monitor.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/ccc.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/bus_rx_flow.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/bus_tx.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/bus_tx_flow.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/configuration.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/descriptor_ibi.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/descriptor_rx.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/descriptor_tx.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/ibi.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/edge_detector.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/i2c_controller_fsm.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/i2c_target_fsm.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/i3c_controller_fsm.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/i3c_target_fsm.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/flow_active.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/flow_standby_i2c.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/controller_standby_i2c.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/controller_standby_i3c.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/controller_active.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/controller_standby.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/controller.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/ctrl/stable_high_detector.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/i3c.sv
      - $COMPILE_ROOT/../../third_party/i3c-core/src/i3c_wrapper.sv
    tops: [i3c_wrapper]
  rtl_lint:
    waiver_files:
      - $MSFT_REPO_ROOT/src/i3c-core/config/design_lint/sglint_waivers
#  cdc:
#    tcl_files:
#      - $COMPILE_ROOT/config/cdc/i3c_wrapper.constraints.tcl
#      - $COMPILE_ROOT/config/cdc/i3c_wrapper.waivers.tcl
