name: caliptra_ss_lib
files:
  # Components
  - src/mcu/config/compile.yml
  - src/riscv_core/veer_el2/config/compile.yml
  - src/i3c-core/config/compile.yml
  - src/integration/config/avery_vip.yml

  # Third Party
  # Caliptra RTL
  - third_party/caliptra-rtl/src/libs/config/compile.yml
  - third_party/caliptra-rtl/src/ahb_lite_bus/config/compile.yml
  - third_party/caliptra-rtl/src/riscv_core/veer_el2/config/compile.yml
  - third_party/caliptra-rtl/src/sha512/config/compile.yml
  - third_party/caliptra-rtl/src/sha256/config/compile.yml
  - third_party/caliptra-rtl/src/doe/config/compile.yml
  - third_party/caliptra-rtl/src/hmac/config/compile.yml
  - third_party/caliptra-rtl/src/soc_ifc/config/compile.yml
  - third_party/caliptra-rtl/src/hmac_drbg/config/compile.yml
  - third_party/caliptra-rtl/src/ecc/config/compile.yml
  - third_party/caliptra-rtl/src/keyvault/config/compile.yml
  - third_party/caliptra-rtl/src/pcrvault/config/compile.yml
  - third_party/caliptra-rtl/src/datavault/config/compile.yml
  - third_party/caliptra-rtl/src/integration/asserts/config/compile.yml
  - third_party/caliptra-rtl/src/sha512_masked/config/compile.yml
  - third_party/caliptra-rtl/src/axi/config/compile.yml
  - third_party/caliptra-rtl/src/ecc/uvmf_ecc/config/compile.yml
  - third_party/caliptra-rtl/src/hmac/uvmf_2022/config/compile.yml
  - third_party/caliptra-rtl/src/keyvault/uvmf_kv/config/compile.yml
  - third_party/caliptra-rtl/src/pcrvault/uvmf_pv/config/compile.yml
  - third_party/caliptra-rtl/src/sha512/uvmf_sha512/config/compile.yml
  - third_party/caliptra-rtl/src/soc_ifc/uvmf_soc_ifc/config/compile.yml
  - third_party/caliptra-rtl/src/integration/uvmf_caliptra_top/config/compile.yml


  # -- Start RNG --
  - third_party/caliptra-rtl/src/caliptra_prim_generic/config/compile.yml
  - third_party/caliptra-rtl/src/caliptra_prim/config/compile.yml
  - third_party/caliptra-rtl/src/lc_ctrl/config/compile.yml
  - third_party/caliptra-rtl/src/aes/config/compile.yml
  - third_party/caliptra-rtl/src/edn/config/compile.yml
  - third_party/caliptra-rtl/src/kmac/config/compile.yml
  - third_party/caliptra-rtl/src/entropy_src/config/compile.yml
  - third_party/caliptra-rtl/src/csrng/config/compile.yml
  # -- End RNG --
  
  # Adams Bridge
  - third_party/caliptra-rtl/submodules/adams-bridge/src/abr_libs/config/compile.yml
  - third_party/caliptra-rtl/submodules/adams-bridge/src/abr_prim_generic/config/compile.yml
  - third_party/caliptra-rtl/submodules/adams-bridge/src/abr_prim/config/compile.yml
  - third_party/caliptra-rtl/submodules/adams-bridge/src/abr_sha3/config/compile.yml
  - third_party/caliptra-rtl/submodules/adams-bridge/src/rej_sampler/config/compile.yml
  - third_party/caliptra-rtl/submodules/adams-bridge/src/rej_bounded/config/compile.yml
  - third_party/caliptra-rtl/submodules/adams-bridge/src/exp_mask/config/compile.yml
  - third_party/caliptra-rtl/submodules/adams-bridge/src/sample_in_ball/config/compile.yml
  - third_party/caliptra-rtl/submodules/adams-bridge/src/decompose/config/compile.yml
  - third_party/caliptra-rtl/submodules/adams-bridge/src/sk_encode/config/compile.yml
  - third_party/caliptra-rtl/submodules/adams-bridge/src/sk_decode/config/compile.yml
  - third_party/caliptra-rtl/submodules/adams-bridge/src/makehint/config/compile.yml
  - third_party/caliptra-rtl/submodules/adams-bridge/src/norm_check/config/compile.yml
  - third_party/caliptra-rtl/submodules/adams-bridge/src/sig_encode_z/config/compile.yml
  - third_party/caliptra-rtl/submodules/adams-bridge/src/sig_decode_z/config/compile.yml
  - third_party/caliptra-rtl/submodules/adams-bridge/src/sigdecode_h/config/compile.yml
  - third_party/caliptra-rtl/submodules/adams-bridge/src/pk_decode/config/compile.yml
  - third_party/caliptra-rtl/submodules/adams-bridge/src/power2round/config/compile.yml
  - third_party/caliptra-rtl/submodules/adams-bridge/src/mldsa_sampler_top/config/compile.yml
  - third_party/caliptra-rtl/submodules/adams-bridge/src/ntt_top/config/compile.yml
  - third_party/caliptra-rtl/submodules/adams-bridge/src/mldsa_top/config/compile.yml
  - third_party/caliptra-rtl/submodules/adams-bridge/src/mldsa_top/uvmf/config/compile.yml

    # Please add your next file/folder above not below the line
  - third_party/caliptra-rtl/src/integration/config/compile.yml
  - src/integration/config/compile.yml
